# Generated by Django 3.1.2 on 2021-04-08 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educators',
            options={'verbose_name_plural': 'Educators'},
        ),
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name_plural': 'Students'},
        ),
        migrations.RenameField(
            model_name='educators',
            old_name='educator_name',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='educators',
            old_name='educator_surname',
            new_name='name',
        ),
        migrations.AddField(
            model_name='educators',
            name='phone',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='educators',
            name='profile_pic',
            field=models.ImageField(default='', upload_to='educator_profile_pic/'),
        ),
        migrations.AddField(
            model_name='educators',
            name='surname',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='educators',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='educator', to=settings.AUTH_USER_MODEL),
        ),
    ]
