# Generated by Django 3.1.2 on 2021-04-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210419_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='advisor',
            field=models.CharField(max_length=100),
        ),
    ]
