# Generated by Django 3.1.2 on 2021-04-14 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_auto_20210408_0719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='student_name',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='student_surname',
            new_name='name',
        ),
        migrations.AddField(
            model_name='students',
            name='phone',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='students',
            name='profile_pic',
            field=models.ImageField(default='', upload_to='student_profile_pic/'),
        ),
        migrations.AddField(
            model_name='students',
            name='surname',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='students',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
    ]
