# Generated by Django 3.1.2 on 2021-04-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210414_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='assignments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='assignments/pdfs/')),
            ],
        ),
    ]
