# Generated by Django 3.1.2 on 2021-04-19 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_assignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='advisor',
            field=models.CharField(default='', max_length=100),
        ),
    ]
