# Generated by Django 3.1.2 on 2021-04-19 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_assignments_advisor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignments',
            options={'verbose_name_plural': 'Assignments'},
        ),
    ]
